<?php
class Resources
{
    /* TODO:
     *  - Meter aquí los TYPE de Telegram
     *  - Ver como referenciar desde todos los PHP sin que falle por clase ya definida
     *  - Mover aquí todos los arrays de insultos y demás mierdas
     *  - ¿Intentar usar espacios de nombres?
     */

    // INSULTOS
    const INSULTO_DIRECTO = [
        'jodido perturbado', 'estúpido', 'retrasado', 'podemita', 'pederasta',
        'enfermo', 'hijo de puta', 'maricón', 'sodomita', 'gilipollas', 'subnormal',
        'aborto', 'judio', 'bebedor de semen', 'soplanucas', 'abrazafarolas',
        'baboso', 'caraculo', 'mascachapas', 'cuerpoescombro', 'zurcefrenillos',
        'cabronazo', 'retrasado', 'muerdealmohadas'
    ];

    const INSULTO_DIRECTO_2 = ['Maldito', 'Jodido', 'Estúpido', 'Condenado', 'Retrasado', 'Podemita'];

    const INSULTO_MADRE = ['zorra', 'puta', 'comerrabos', 'cerda'];

    const WEBS_PORNO = ['xvideos.com', 'pornhub.com', 'xhamster.com', 'redtube.com'];

    // FILETE
    const GIF_FILETE_BAMBOLEO_SANSE = 'CgADBAADKQIAAnteIFE5UYFYJX2qixYE';
    const GIF_FILETE_BAMBOLEO_PISCINA = 'CgADBAADUAQAAuIH2FIvmmtra2PQghYE';
    const GIF_FILETE_PONIENDOSE_SOMBRERO_BOCA = 'CgADBAADhQYAApvyeVLK8VCcjFDIahYE';
    const GIF_FILETE_ACERCANDOSE_EN_LA_OSCURIDAD = 'CgADBAAD2QQAAu5muFCiVPNQMvz5dRYE';

    // CAS
    const GIF_CAS_PRIMERISIMO_PRIMER_PLANO = 'CgADBAADhgEAAkBv0FK6Z8T5WtvXyhYE';
    const GIF_CAS_EXTRATITANIO_HAWAIIAN = 'CgADBAADNQMAAgJLIVOpud42f62NyBYE';
    const IMG_CAS_GANGSTER_PURO = 'AgADBAADLbExG6uCfgABO7d46OcKzQkVuo8wAATDrhyVPZbKfktbAAIC';

    // NANO
    const GIF_NANO_PINZAS = 'CgADBAADRQEAAp8ZCFOlOH2wfB8iwhYE';
    const GIF_NANO_ABANICO_BODA = 'CgADBAAD-wgAAruMgFFshOqnSV3rfBYE';
    const GIF_NANO_CLEARLY_SOCIALIST = 'CgADBAADPwIAAquCfgABqSIVDkdKUb8WBA';

    // CARRACEDO
    const GIF_CARRACEDO_OTRO_PICK = 'BQADBAADOQEAAphMPgABREm9f5CcR-kC';
    const GIF_CARRACEDO_HOLA_VERTICAL = 'CgADBAADXAYAAmyRKFDQ8CNbpMg3DxYE';

    // KETU
    const IMG_KETU_NAVAS_HOLA_KETU = 'AgADBAADtbExG6uCfgABLrwSmy2LSv8U1IwwAAQ_de836O5RLh3YAAIC';
    const IMG_KETU_VALE_TIO = 'AgADBAADs7ExG6uCfgABNelLZA68mblL0owwAATnURFjObRacZTZAAIC';
    const IMG_KETU_HA_APOSTADO_VICENTE_YA = 'AgADBAADLLExG6uCfgAB0UBRGzF7sb96C2swAAS7hCl_X6wqS9ByAQABAg';

    // PACO
    const GIF_PACO_CABALLO_LOCO_SILLA = 'CgADBAAD0AIAAnoJiVLJQa7FfA8Y5xYE';

    // VICENTE
    const GIF_VICENTE_AGRESION_BUS_BODA = 'CgADBAADhQUAAgbukVEBve9w3nbnNxYE';

    // BARTOL
    const GIF_BARTOL_BANDERA_EUROPA_VENGUE = 'CgADBAADSAMAAlB0oFDCb915X2W1VRYE';
    const GIF_BARTOL_ALAS_BARCELONA = 'CgADBAADWQEAAphMPgAByRJsQf96PWkWBA';
    const IMG_BARTOL_NO_GUS = 'AgADBAADr7ExG6uCfgABRKEQrm8ULhfcco8wAAQ5D9K2nU6X0IFfAAIC';

    // ORI
    const GIF_ORI_BAILE_RANDOM_TRAJE_CAMISA = 'CgADBAADIwYAAvWfuVBKd6kbKnnqoRYE';

    // AGE
    const GIF_AGE_BAILE_RANDOM = 'BQADBAADWAEAAphMPgAB-oBIaV81Y04C';    
    const GIF_AGE_MINI_QUE_NOS_QUITEN_LO_BAILAO = 'CgADBAAEAgACq4J-AAExT8pAS0OuaRYE';
    const IMG_AGE_IKER_HOLA_AGE = 'AgADBAADtLExG6uCfgABPI6QTh8Q4fpHQnEwAARy8nYUUSRw2Lq2AQABAg';

    // RICHY
    const GIF_RICHY_BAILANDO_MASCARA_PROBOSCIS = 'CgADBAADhwEAAs-FmVI0EswpkrpGvRYE';
    const GIF_RICHY_ME_SUDA_LOS_COJONES = 'CgADBAAD9QIAAqkq6FJaGufnTE-q7BYE';
    const GIF_RICHY_BAILE_MALTA_CAMISETA_AMARILLA = 'CgADBAADZgQAAtnN-FBs7NYhGSMEDxYE';
    
    // RINCON
    const GIF_RINCON_CORTEN = 'CgADBAADyAIAAlKXEFLgc7w96-lNHxYE';
    const GIF_RINCON_BAILANDO_BODA = 'CgADBAADjgQAAoIVuVKBtxmIf9m6KhYE';

    // VARIOS
    const GIF_BAILE_BARCO_SICILIA = 'CgADBAADrQQAAsqjaFJnNJM3tQ52jRYE';
    const GIF_MASCARAS_RAVE_NORUEGA = 'CgADBAADHAADCdoIUu56gllhbkZgFgQ';
    const GIF_MASCARAS_BAILE_BODA = 'CgADBAADcAQAAmjGuFGBt0xNDD0yWhYE';
    const GIF_FIESTA_HOMO_SICILIA = 'CgADBAADXwQAAuyaMVJ0emB6xIwBYE';
    const GIF_HOLA_BALCON_SICILIA = 'CgADBAADYAUAAhhQoFJTZN8T7kqykhYE';
    const GIF_NANO_LUCHO_CONECTA_NAZI = 'CgADBAAD3AQAApUXKVMzll3BUkFighYE';

    // MISC
    const STK_LUCAS_VAZQUEZ = 'CAADBAADyQADmw-YAAEtDh4CzdAP5xYE';
    const STK_FRANCO_CONMIGO_NO_PASABA = 'BQADBAAD7AAD-WxHAtGrH8UmWiiXAg';
    const GIF_APLAUSO_MARIANO = 'BQADBAADVwIAAmCIgQABk85Zb6xxMZwC';
    const GIF_MI_PENALTITO_CRISTIANO = 'BQADBAADtwADmEw-AAHFpvL_faHg5QI';
    const GIF_APLAUSO_CIUDADANO_KANE = 'BQADBAADuAADmEw-AAFENNvXv3KlQgI';
    const GIF_ERNESTO_SEVILLA_VAYA_MIERDA = 'BQADBAADMgADmw-YAAE4pcdXZXF0FgI';
    const GIF_JURASSIC_PARK_ENTRADA = 'BQADBAADJR0AAsseZAf3QgvdLNg82AI';
    const GIF_GATO_ACARICIADO = 'BQADBAAD6gADmEw-AAGGLIPvh6gpqwI';
    const GIF_PEDRO_SANCHEZ_RIENDO = 'BQADBAADUQAECiQBwXY8yQTw4psC';
    const GIF_BENITEZ_FAT_SPANISH_WAITER_SOMBRERO = 'BQADBAADMAEAAquCfgABhqhRqhpC5agC';
    const GIF_TETAS_VUELTA_CICLISTA = 'CgADBAADkAYAAihAGVOm0ZFK-H4JmhYE';
    const GIF_LLULL_PALMAS_VAMOS = 'CgADBAADgwEAAlKL9FPaIaEsy4bQgxYE';
    const GIF_PERRO_TECLEANDO = 'CgADBAADiAEAA5kcUI2DrRd86X-KFgQ';
    const GIF_GOL_SENOR_CABALLO_BIPEDO = 'BQADBAADGwEAAphMPgABI26EAcZ0dg0C';    
    const GIF_GORDO_BAMBOLEANDOSE = 'CgADBAADC6kAAtQXZAchOcCpwE1b6BYE';
    const GIF_NO_RACISMO_BANDERIN_CHAMPIONS = 'CgADBAADfQEAAhhr-FJzGK8Valo2QBYE';
    const GIF_NO_RACISMO_CARAS_HITLER = 'CgADBAAD0QUAAhkuIFBQC5slBQOM7hYE';
    const GIF_DICAPRIO_MAKE_IT_RAIN = 'CgADBAADTZ8AAjQbZAdTQtGqizpc4BYE';
    const GIF_NIGGA_MAKE_IT_RAIN = 'CgADBAADmwADW1rsUtJY9Hf2GFVSFgQ';
    const GIF_JOAQUIN_VAR = 'CgADBAADbgADmFeNUpOunOm97dFgQ';
    const GIF_PALMERAS_HURACAN = 'CgADBAADagEAArxVHVC3qXwwRt0oeBYE';
    const GIF_NICOLAS_CAGE_MELENA_VIENTO = 'CgADBAADRgEAAtqXbVOsFJWNdRd-0RYE';
    const GIF_SCHWARZENEGGER_TITS = 'CgADBAADnAMAAikXZAdy1pWF-FGOzhYE';
    const GIF_TIO_CON_SENAL_DE_STOP = 'CgADBAAD-AUAAkHWQFET1GEonvEAAW4WBA';
    const GIF_FERDINAND_SI_OTRA_RESACA = 'CgADBAADUAUAAkjOqVIj5XBCLG-dLBYE';
    const GIF_FERDINAND_NO_OS_HUELE_A_MERLA = 'CgADBAADXgEAAgmKMVPJ5JKX-UHCrhYE';
    const GIF_FERDINAND_VENGA_VENGA_OTRA_MERLA = 'CgADBAADxQADW42ZUXLse2R9PD-LFgQ';
    const GIF_FORREST_GUMP_SALUDANDO = 'CgADBAADXgADugFdUb-9FlqWDnZiFgQ';
    const GIF_ARABES_BAILANDO_VENGUE = 'CgADBAADKgMAAm4WqVLDIDqqf3XrBhYE';
    const GIF_GREASE_TELL_ME_MORE = 'CgADBAADVQADmyHlUFJKKqP7y8MpFgQ';
    const AUD_JURASSIC_PARK = 'BQADBAADVAEAAphMPgABNc-CEJQck9oC';
    const AUD_BUENAS_NOCHES_Y_BUENA_SUERTE = 'BQADBAADeQEAAphMPgABO9S1sNpcpYgC';
    const AUD_PEM_JOSE_BRETON = 'BQADBAADawEAAquCfgABAhruCPned4AC';
    const AUD_STIHL = 'BQADBAADOgEAAphMPgABZZKRawyaaBwC';
    const AUD_WOLOLO = 'BQADBAADOQADmw-YAAEVi-CBIwOYXQI';
    const AUD_GOL_MORSE = 'BQADBAADnAADmw-YAAGj6L0TKXyxjAI';
    const IMG_ADMIRAL_ACKBAR_TRAP = 'AgADBAADK7ExG6uCfgAB9rTpspMp9VRGYGkwAAS8GdFc47A_whSFAQABAg';
    const IMG_IGLESIAS_SE_HA_IDO_LA_CASTA_YA = 'AgADBAADtrExG6uCfgAB-HBYDek-QkN_mo8wAARqlUj5CBNq9idfAAIC';
    const IMG_THEODEN_NO_TIENES_PODER = 'AgADBAADKqkxG5hMPgABj_DlPCsJq_QnvI8wAATxeRhugBnP6DH_AAIC';
}
?>